name: Build and Deploy
on: push

jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - name: Checkout
          uses: actions/checkout@v3
          # with:
          #   fetch-depth: 0
            # token: ${{ secrets.GP_TOKEN }}

        # Git configure
        - name: Setup git configs
          run: |
            git checkout master
            git config --global user.name "akshaychavan7"
            git config --global user.email "akshaychavan.kkwedu@gmail.com"

        - name: Build and Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            # ACCESS_TOKEN: ${{ secrets.GP_TOKEN }}
            branch: gh-pages # The branch the action should deploy to.
            folder: src # The folder the action should deploy.

        # # Deploy Firebase Hosting
        # - name: Deploy Firebase Hosting
        #   uses: w9jds/firebase-action@master
        #   with:
        #     args: deploy --only hosting:mhmzdev-666 # ID of project at firebase
        #   env:
        #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        #     PROJECT_PATH: ./